# Installing software for proxmox on Debian 12:
# https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_12_Bookworm
---
- name: Upgrade current distribution
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

# Apparently this is now deprecated and no longer works, wonderful.
# - name: Add Proxmox Repository Key
#   ansible.builtin.apt_key:
#     validate_certs: true
#     url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
#     state: present

- name: Add Proxmox Repository Key
  ansible.builtin.get_url:
    url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
    mode: '0644'
    force: true

- name: Add Proxmox apt repository
  ansible.builtin.apt_repository:
    validate_certs: false
    repo: deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription
    filename: pve-no-subscription
    state: present

- name: Update apt cache with new repository
  ansible.builtin.apt:
    update_cache: true
    autoremove: true
    upgrade: true

- name: Create /boot/pve for proxmox kernels
  ansible.builtin.file:
    path: /boot/pve
    state: directory
    mode: '0644'
    owner: root
    group: root

- name: Create /mnt/pve for proxmox kernels
  ansible.builtin.file:
    path: /mnt/pve
    state: directory
    mode: '0644'
    owner: root
    group: root

- name: Create bindmount from /mnt/pve to /boot/pve
  ansible.posix.mount:
    src: /mnt/pve
    path: /boot/pve
    state: mounted
    opts: bind
    fstype: none
    boot: true
    backup: true
  register: add_mount

# - name: Update fstab
#   ansible.builtin.shell: |
#     genfstab
#   when: add_mount.changed

# Note: learned this the hard way: Your EFI partition cannot be a VFAT partition 
# since this package tries to symlink kernels in /boot/pve, and vfat does not support
# symlinks :(
# https://forum.proxmox.com/threads/ln-failed-to-create-symbolic-link-boot-pve-vmlinuz-5-11-operation-not-permitted.95545/
- name: Install proxmox kernel
  ansible.builtin.apt:
    name:
    - pve-kernel-6.2
    state: present
  register: kernel_installed

- name: Reboot after kernel installation
  ansible.builtin.reboot:
    reboot_timeout: 3600
  when: kernel_installed.changed

- name: Install proxmox
  ansible.builtin.apt:
    name:
    - proxmox-ve
    - open-iscsi
    - ifupdown2
    - chrony
    - postfix
    state: latest

- name: Remove vanilla debian kernel
  ansible.builtin.apt:
    name:
    - linux-image-amd64
    - 'linux-image-6.1*'
    state: absent
  register: remove_old_kernel

- name: Update grub after kernel removal
  ansible.builtin.shell: |
    update-grub
  when: remove_old_kernel.changed

- name: Remove os-prober
  ansible.builtin.apt:
    name:
    - os-prober
    state: absent
