---
- name: Add Proxmox Repository Key
  ansible.builtin.apt_key:
    validate_certs: false
    url: http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg
    state: present
    file: /etc/apt/trusted.gpg.d/proxmox-ve-release-6.x.gpg
    # keyring: /etc/apt/trusted.gpg.d/google-k8s.gpg

- name: Add Proxmox apt repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://download.proxmox.com/debian/pve buster pve-no-subscription
    filename: pve-install-repo
    state: present
    validate_certs: false

- name: Update apt cache with new repository
  ansible.builtin.apt:
    update_cache: true
    autoremove: true
