---

# Useful debugging things:
# https://askubuntu.com/questions/1488018/nvidia-cuda-installation-package-conflicts
# https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

- name: Install CUDA on Ubuntu Machine
  hosts: cuda
  become: true
  tasks:
  - name: Add NVIDIA Repository Key
    ansible.builtin.get_url:
      url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-archive-keyring.gpg
      dest: /etc/apt/trusted.gpg.d/cuda-archive-keyring.gpg
      mode: '0644'
      force: true

  - name: Add NVIDIA Apt Repository
    ansible.builtin.apt_repository:
      validate_certs: true
      repo: deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /
      filename: cuda-ubuntu2204-x86_64
      state: present

  - name: Add NVIDIA Repository Preference Pin
    ansible.builtin.get_url:
      url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
      dest: /etc/apt/preferences.d/cuda-repo-pin-600
      mode: '0600'
      force: true

  - name: Install CUDA Stuff
    ansible.builtin.apt:
      name:
      - cuda
      - nvidia-gds
      update_cache: true
      state: latest
    register: cuda_install

  - name: Reboot server
    ansible.builtin.reboot:
      reboot_timeout: 5000
    when: cuda_install.changed
