---

- name: Fix proxmox services so things work
  hosts: proxmox
  become: true
  tasks:

  - name: Restart proxmox services
    ansible.builtin.systemd_service:
      name: "{{ item }}.service"
      state: restarted
      enabled: true
    loop:
    - pvedaemon
    - pveproxy
    - pvestatd
    