---

- name: Install HAproxy config Directory
  ansible.builtin.file:
    path: /etc/haproxy
    state: directory
    mode: '0755'

- name: Install HAproxy certs Directory
  ansible.builtin.file:
    path: /etc/haproxy/certs
    state: directory
    mode: '0755'

- name: Install cryptography
  ansible.builtin.apt:
    name:
    # - python3-pip
    - python3-cryptography
    state: present

# - name: Install cryptography library pip3
#   ansible.builtin.pip:
#     name:
#     - cryptography

- name: Generate private key (proxmox.cloud.ou.edu)
  community.crypto.openssl_privatekey:
    path: /etc/haproxy/certs/proxmox-cloud.key
    type: ECC
    curve: secp256r1
    state: present

- name: Generate CSR (proxmox.cloud.ou.edu)
  community.crypto.openssl_csr:
    path: /etc/haproxy/certs/proxmox-cloud.csr
    privatekey_path: /etc/haproxy/certs/proxmox-cloud.key
    country_name: US
    organization_name: OU
    common_name: proxmox.cloud.ou.edu
    state: present

- name: Generate self-signed cert (proxmox.cloud.ou.edu)
  community.crypto.x509_certificate:
    path: /etc/haproxy/certs/proxmox-cloud
    privatekey_path: /etc/haproxy/certs/proxmox-cloud.key
    csr_path: /etc/haproxy/certs/proxmox-cloud.csr
    provider: selfsigned
    state: present

- name: Install Haproxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
    owner: root
    group: root
    backup: true
  register: haproxy_config

- name: Install Haproxy
  ansible.builtin.apt:
    name:
    - haproxy
    state: latest
  register: haproxy_install

- name: Enable HAProxy
  ansible.builtin.systemd_service:
    name: haproxy.service
    enabled: false
    state: stopped
    daemon_reload: true
