---

- name: Get Zerotier Install Script
  ansible.builtin.get_url:
    url: https://install.zerotier.com
    dest: /root/proxmox-installer.sh
    mode: '0700'

- name: Install zerotier
  ansible.builtin.command:
    cmd: bash /root/proxmox-installer.sh
    creates: /usr/sbin/zerotier-one

- name: Enable Zerotier
  ansible.builtin.systemd_service:
    name: zerotier-one.service
    enabled: true
    # state: restarted
    state: started
    daemon_reload: true

- name: Join Network
  ansible.builtin.shell:
    zerotier-cli join {{ zerotier_network }}
  ignore_errors: true
