---

- name: Install Zerotier
  become: true
  ansible.builtin.command:
    cmd: curl -s https://install.zerotier.com | bash
    creates: /usr/bin/zerotier-one

- name: Enable Zerotier
  ansible.builtin.systemd_service:
    name: zerotier-one.service
    enabled: true
    state: restarted
    daemon_reload: true

- name: Join Network
  ansible.builtin.shell:
    zerotier-cli join {{ zerotier_network }}
  ignore_errors: true
