---

# - name: Install cargo
#   ansible.builtin.apt:
#     name:
#     - cargo
#     update_cache: true
#     state: latest

- name: Install dependencies for zeronsd
  ansible.builtin.apt:
    name:
    - openssl
    - libssl-dev
    - pkg-config
    state: latest

# - name: Check if rustup exists
#   ansible.builtin.command: which rustup
#   register: rustup_exists
#   ignore_errors: true

# - name: Install rustup
#   ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
#   when: rustup_exists.rc == 1

- name: Install zeronsd binary
  ansible.builtin.command: cargo install zeronsd
