---

- name: Install mellanox tooling
  hosts: all
  become: true
  tasks:
  
  - name: Install mstflint
    ansible.builtin.apt:
      name:
      - mstflint
      state: latest

  - name: Install this prereq crap
    ansible.builtin.apt:
      update_cache: true
      name:
      - gcc 
      - make 
      - dkms 
      # - linux-headers
      # - linux-headers-generic
      state: latest

  - name: Download Mellanox packages
    ansible.builtin.get_url:
      url: https://www.mellanox.com/downloads/MFT/mft-4.26.0-93-x86_64-deb.tgz
      dest: /root/mft.tgz
      mode: '0644'

  - name: Add package directory
    ansible.builtin.file:
      path: /root/mft_unpack
      state: directory

  - name: Unpack Mellanox packages
    ansible.builtin.unarchive:
      remote_src: true
      src: /root/mft.tgz
      dest: /root/mft_unpack

  - name: Download driver
    ansible.builtin.get_url:
      url: https://www.mellanox.com/downloads/ofed/MLNX_EN-23.10-0.5.5.0/mlnx-en-23.10-0.5.5.0-debian12.1-x86_64.tgz
      dest: /root/mft_driver.tgz

  - name: Add package directory
    ansible.builtin.file:
      path: /root/mft_driver_unpack
      state: directory

  - name: Unpack Mellanox packages
    ansible.builtin.unarchive:
      remote_src: true
      src: /root/mft_driver.tgz
      dest: /root/mft_unpack

  - name: Install Driver package
    ansible.builtin.command: echo "y" | ./root/mft_unpack/mlnx-en-23.10-0.5.5.0-debian12.1-x86_64/install --skip-distro-check
