---

- name: Install mellanox tooling
  hosts: all
  become: true
  tasks:
  
  - name: Install mstflint
    ansible.builtin.apt:
      name:
      - mstflint
      state: latest

  - name: Install this prereq crap
    ansible.builtin.apt:
      update_cache: true
      name:
      - gcc 
      - make 
      - dkms 
      # - linux-headers
      # - linux-headers-generic
      state: latest

  - name: Download Mellanox packages
    ansible.builtin.get_url:
      url: https://www.mellanox.com/downloads/MFT/mft-4.26.0-93-x86_64-deb.tgz
      dest: /root/mft.tgz
      mode: '0644'

  - name: Add package directory
    ansible.builtin.file:
      path: /root/mft_unpack
      state: directory

  - name: Unpack Mellanox packages
    ansible.builtin.unarchive:
      remote_src: true
      src: /root/mft.tgz
      dest: /root/mft_unpack

  # - name: Install Mellanox packages
  #   ansible.builtin.command: ./root/mft_unpack/mft-4.26.0-93-x86_64-deb/install.sh 

  - name: Install Mellanox packages
    ansible.builtin.command: dpkg -i /root/mft_unpack/mft-4.26.0-93-x86_64-deb/DEBS/mft_4.26.0-93_amd64.deb
